### ISSUE TITLE
ODPC: Lege dotnet applicatie met vue inrichten en deployen

### ISSUE THREAD

**Issue by RutgerICATT** [GeneriekPublicatiePlatformWoo/Openbaar-Documenten-Publicatie-Component#16]
**Description (why)**

**Acceptance criteria (what)**

**Specific details (how)**
- Postgres instance op OTA-DB Inrichten (Pascal / Vincent) => 3 punten?
- Lege dotnet website met vue in github => 1 punt
  - CI/CD in Azure DevOps => 1 punt
  - IIS Website op OTA-WEB
  - Postgres DB op OTA-DB

**Test plan**

**Comment by mstokericatt** [comment]
getest en akkoord
