### ISSUE TITLE
ODPC: Identity Provider inrichten

### ISSUE THREAD

**Issue by RutgerICATT** [GeneriekPublicatiePlatformWoo/Openbaar-Documenten-Publicatie-Component#17]
**Description (why)**

**Acceptance criteria (what)**

**Specific details (how)**

Azure AD inrichting
Net als bij KISS, eigen Azure AD met mogelijkheid om gebruikers uit te nodigen

2 punten

OF

Keycloak installeren en inrichten ==> GAAN WE WAARSCHIJNLIJK NIET DOEN
Maykin vragen om schatting, hulp bij installeren en inrichten - Beheerder en Ambtenaar - Gebruik clientRoles, in lijn met ZAC - Groepen zijn te beheren door gemeente

5 punten

**Test plan**

**Comment by felixcicatt** [comment]
Nog te overleggen: keuze wel of niet koppelen met een IdentityProvider voor lijsten van groepen/gebruikers

**Comment by mstokericatt** [comment]
de eerste variant is gerealiseerd en getest.
getest met een tijdelijke andere AD, er lijkt iets mis te zijn gegaan bij een vakantie overdracht, waardoor er momenteel geen toegang is tot de hiervoor aangemaakte AD. volgende week even de aanpassen en de juiste ad koppelen. verder is de story klaar
