### ISSUE TITLE
ODPC: Opslag dynamische gebruikersgroepen

### ISSUE THREAD

**Issue by felixcicatt** [GeneriekPublicatiePlatformWoo/Openbaar-Documenten-Publicatie-Component#20]
**Acceptatie criteria (what)**

- Er is een back-end waarin gegevens over gebruikersgroepen opgeslagen kunnen worden.
- Een gebruikersgroep moet gecreëerd, geraadpleegd, gewijzigd en verwijderd kunnen worden.
- Het aanmaken / wijzigen / verwijderen van een groep wordt gelogd
  - indien #6 al is uitgevoerd, hier logging gelijk toevoegen
  - indien #6 nog niet is uitgevoerd, toevoegen aan de lijst met te implementeren logging
- Een gebruikersgroep heeft een `uuid`, een `naam` (verplicht, uniek) en een `omschrijving` (optioneel) (attribuutnamen zijn niet heilig).
- Op een gebruikersgroep kan worden vastgelegd voor welke **organisaties** (opgehaald uit de ODRC of mock) deze groep mag publiceren.
- Op een gebruikersgroep kan worden vastgelegd op welke **informatiecategorieën** (opgehaald uit de ODRC of mock) deze groep mag publiceren.
- Op een gebruikersgroep kan worden vastgelegd op welke **thema's** (opgehaald uit de ODRC of mock) deze groep mag publiceren.
- De documentatie is bijgewerkt
- Een grafisch datamodel van de database is beschikbaar / bijgewerkt (op GitHub of Read the Docs of elders)

**Specific details (how)**
We gaan gebruikersgroepen opslaan in de database van ODPC. Daar is al een voorziening voor getroffen in #5. In deze story regelen we API-endpoints waarmee je groepen kan aanmaken, wijzigen en verwijderen. 

Voor front-end, zie #36 .

**Taken**

- [x] `Omschrijving` veld toevoegen aan model groep
- [x] `Naam` en `omschrijving` opnemen in endpoint voor updaten groep
- [x] Api endpoint voor aanmaken nieuwe groep
- [x] Api endpoint voor verwijderen groep
- [x] ERD schema maken [met behulp van pgadmin](https://www.enterprisedb.com/blog/create-erd-pgadmin-4)

**Comment by felixcicatt** [comment]
Een eerste versie van de backend staat in de branch [dynamische-groepen](https://github.com/GeneriekPublicatiePlatformWoo/Openbaar-Documenten-Publicatie-Component/tree/dynamische-groepen). Voorstel: deze story samen met #36 oppakken. @nijmra kan dan aan de front-end werken en waar nodig de backend aanpassen, en @mstokericatt kan dan zowel de backend als de frontend reviewen.

**Comment by MarcoKlerks** [comment]
> Een grafisch datamodel van de database is beschikbaar / bijgewerkt (op GitHub of Read the Docs of elders)

@mstokericatt  Waar kan ik deze vinden?

**Comment by nijmra** [comment]
@MarcoKlerks [erd.png](https://github.com/GeneriekPublicatiePlatformWoo/Openbaar-Documenten-Publicatie-Component/blob/main/erd.png)
