### ISSUE TITLE
ODPC: Meerdere documenten in het publicatieformulier

### ISSUE THREAD

**Issue by felixcicatt** [GeneriekPublicatiePlatformWoo/Openbaar-Documenten-Publicatie-Component#23]
Als medewerker wil ik meer dan een documenten aan een publicatie kunnen hangen, zodat ik bijvoorbeeld bijlagen bij een besluit kan toevoegen. Of een Woo-verzoek, plus besluit, plus bijlagen conform de Woo openbaar kan maken. 

**Acceptatie criteria**
- Een medewerker ziet welke documenten er al aan de publicatie zijn gekoppeld,
- Een medewerker kan een of meer bestanden uploaden,
- De geüploade bestanden worden onder elkaar getoond,
- De gebruiker kan één-voor-één de documenten voorzien van de juiste metadata (bijv. in tabel-vorm)
- De gebruiker kan zien welke documenten wel/niet al van metadata zijn voorzien, zodat hij/zij weet welke nog moeten.
- Bestanden kunnen via een verkenner opgezocht en geselecteerd worden (bv op een netwerk-schijf),
- Bestanden kunnen via drag-and-drop geüpload worden.
- Een bestand kan verwijderd worden (bijv. per ongeluk het verkeerde bestand geselecteerd)
- Foutmelding als een bestand niet geüpload kan worden,
- Foutmelding als het ophalen van / schrijven naar de ODRC niet is gelukt.
- Foutmelding als het bestandformaat niet wordt ondersteund (obv de waardelijst `format` uit de registratiecomponent / mock)

**Taken**

**Randvoorwaarden**
- #22 is uitgevoerd

**Notities**
- Er waren twee scenario's. Scenario B dekte ook scenario A af dus die heb ik verwijderd.

<mark>Er is nog niet nagedacht over hoe we op een gebruiksvriendelijke manier meerdere documenten in het formulier gaan tonen. je vindt dit dus ook nog NIET terug in het scherm `Publiceren` in [de wireframe](https://app.uizard.io/p/8dd0f9fa/fullscreen)</mark>

**Comment by MarcoKlerks** [comment]
@nijmra 

Testresultaten:

1. Uploaden van docx.-, xlsx- en pdf-bestand gingen goed. Uploaden van jpeg- en zip-bestand gaven een foutmelding. (Ik vermoed dat dit ligt aan de mock-up van de filetypes).
2. Uploaden meerdere bestanden ging goed. Geprobeerd met 13 bestanden.

Niet kunnen testen:

1. _"Foutmelding als het ophalen van / schrijven naar de ODRC niet is gelukt."_

Nieuwe wensen (mogelijk aparte user stories van maken):

1. Als ik een of meerdere bestanden heb geüpload, verdwijnt de mogelijkheid om nog meer bestanden te uploaden. Ik moet dan eerst opslaan, de publicatie weer opnieuw openen en dan kan ik pas nog meer documenten toevoegen. Graag zou ik direct na het uploaden van een of meer bestanden nog meer bestanden willen kunnen toevoegen.
2. De bestandsnaam minus de extensie wordt automatisch overgenomen als waarde in `Titel` en kan vervolgens door de gebruiker gewijzigd worden. Dit vermindert de administratieve last.
3. Bij het uploaden van documenten wordt eerst alleen het veld `Titel` getoond om in te vinden. Daaronder staat een link / knop "Meer details". Als daarop geklikt wordt kunnen de optionele velden ook ingevuld worden. Dat helpt het scherm overzichtelijk te houden als een relatief groot aantal documenten geüpload worden.
4. Na het uploaden staat bovenin "Nieuw: <bestandsnaam>". Ik zou deze aan willen kunnen klikken, waarna het bestand weer wordt gedownload. Zo kan ik bij twijfel verifiëren of ik het goede bestand heb geüpload.
