### ISSUE TITLE
ODPC: Publicatie annuleren

### ISSUE THREAD

**Issue by felixcicatt** [GeneriekPublicatiePlatformWoo/Openbaar-Documenten-Publicatie-Component#28]
In het formulier waarmee je kunt publiceren moet een optie komen om te Annuleren.  Je gaat dan terug naar de pagina waarop de eigen publicaties getoond (gaan) worden

Zie scherm `Publiceren` in [de wireframe](https://app.uizard.io/p/8dd0f9fa/fullscreen)

**Comment by MarcoKlerks** [comment]
Opgenomen in #34
