### ISSUE TITLE
ODPC: formulier voor minimale publicatie

### ISSUE THREAD

**Issue by felixcicatt** [GeneriekPublicatiePlatformWoo/Openbaar-Documenten-Publicatie-Component#34]
Als ambtenaar wil ik een nieuwe publicatie aan kunnen maken, zodat ik conform de Woo een of meer documenten openbaar kan maken

**Acceptance criteria (what)**

- Een medewerker ziet na het inloggen o.a. een knop voor het aanmaken van een nieuwe publicatie.
- Na het klikken op die knop krijgt de medewerker een regsitratie-scherm te zien.
- Hierop kan hij/zij de volgende velden invullen:
  - "Korte titel"
    - Optioneel veld
    - Eén regel groot
  - "Officiële titel"
    - Verplicht veld
    - Eén regel groot
  - "Omschrijving" 
    - Optioneel veld
    - Tekstblok
  - De gebruiker kan de registratie opslaan of annuleren.
  - Na opslaan of annulering keert de gebruiker terug naar het vorige scherm.

**Specific details (how)**
Voorstel is om met een mock te werken, dus nog geen koppeling met de ODRC en dus ook nog geen mogelijkheid om het resultaat in te zien. De koppeling regelen we in #35 .

In eerste instantie komen alleen de volgende velden van de publicatie in het formulier: 
- [officieleTitel](https://standaarden.overheid.nl/tooi/doc/tooi-ontologie/#property-shape-informatieobject-officieletitel)
- [verkorteTitel](https://standaarden.overheid.nl/tooi/doc/tooi-ontologie/#property-shape-informatieobject-verkortetitel)
- [omschrijving](https://standaarden.overheid.nl/tooi/doc/tooi-ontologie/#property-shape-informatieobject-omschrijving)

Zie scherm Publiceren in [de wireframe](https://app.uizard.io/p/8dd0f9fa/fullscreen)

Voorstel voor POST endpoint voor publicaties
```yaml
paths:
  /api/v1/publicaties:
    post:
        requestBody:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NieuwePublicatie'
          required: true
components:
  schemas:
    NieuwePublicatie:
      type: object
      required:
        - officieleTitel
      properties:
        officieleTitel:
          type: string
        verkorteTitel:
          type: string
        omschrijving:
          type: string
```

**Test plan**

**Tasks**

**Comment by MarcoKlerks** [comment]
Gecorrigeerd in de acc. criteria: de officiële titel is een verplicht veld en niet de (ver)korte titel. Dit vanwege DiWoo-specificaties.
