### ISSUE TITLE
ODPC: minimale publicatie versturen naar Registratiecomponent

### ISSUE THREAD

**Issue by felixcicatt** [GeneriekPublicatiePlatformWoo/Openbaar-Documenten-Publicatie-Component#35]
**Acceptance criteria (what)**
 
- Nieuwe publicaties (#34) worden opgeslagen in het ODRC [via de API](https://github.com/orgs/GeneriekPublicatiePlatformWoo/projects/1/views/16?pane=issue&itemId=74959350).
- ~~Documentatie van alle configuratie / environment variabelen met voorbeelden. In eerste instantie in installation.md bestand in de ODPC github repository~~ nog niet beschikbaar in het register. verhuisd naar #66 

**Specific details (how)**
In #34 hebben we een formulier gemaakt voor een minimale publicatie. In deze story gaan we de inhoud van dit formulier naar de Registratiecomponent sturen. Hiervoor moeten we het verzoek dat vanuit de frontend komt, in de backend verrijken met de volgende headers (implementeren headers is verhuisd naar #66 ):
- `Audit-User-Id`: de unieke identifier van de ingelogde gebruiker. Dit is een claim uit de JWT token. Welke claim gekozen wordt, is te configureren met de omgevingsvariabel `OIDC_ID_CLAIM_TYPE`
- `Audit-User-Display-Name`: de naam van de ingelogde gebruiker. Dit is een claim uit de JWT token. Welke claim gekozen wordt, is te configureren met de omgevingsvariabel `OIDC_NAME_CLAIM_TYPE`
- `Audit-Toelichting`: `Publicatie geregistreerd`
- `Token` (api key, te configureren met een omgevingsvariabel)

Foutafhandeling: afspraak maken over stramien rondom vriendelijke foutmeldingen vanuit de registratiecomponent die we aan de gebruiker kunnen tonen.

**Notitie**
Versturen van publicatie naar ODRC doen we parallel aan de Mock, die blijft bestaan totdat ook ophalen via ODRC loopt

**Test plan**

- Publicatie is na opslaan zichtbaar in de beheerinterface van de Registratiecomponent van Maykin

**Tasks**

**Comment by MarcoKlerks** [comment]
De mutatie van een publicatie gaat nog niet naar het ODRC. Is dat bewust? Ik zie geen andere user story daarvoor....

**Comment by nijmra** [comment]
> De mutatie van een publicatie gaat nog niet naar het ODRC. Is dat bewust? Ik zie geen andere user story daarvoor....

Ja, dat is scope van deze story. We halen nog geen publicaties op om die dan weer te kunnen muteren. Daar hebben we story #68

**Comment by MarcoKlerks** [comment]
#68 op Refinement gezet.
