### ISSUE TITLE
ODPC: front-end dynamische gebruikersgroepen

### ISSUE THREAD

**Issue by MarcoKlerks** [GeneriekPublicatiePlatformWoo/Openbaar-Documenten-Publicatie-Component#36]
**Toelichting**

In #5 is deel van de front-end gebouwd voor gebruikersgroepen. In #20 wordt (in een latere sprint) een back-end gerealiseerd. In deze story maken we de front-end af en zorgen we dat deze met de back-end koppelt.

**Acceptatie criteria**

- Als beheerder wil ik in het ODPC toegang tot een beheer-interface.
- In de beheer-interface kan ik naar de gebruikersgroepen.
- Bij de gebruikersgroepen zie ik welke gebruikersgroepen er zijn opgeslagen (#20 )
- Ik kan een nieuwe gebruikersgroep aanmaken.
- Ik kan van een gebruikersgroep de `naam` en/of `omschrijving` wijzigen.
- Ik kan een gebruikersgroep openen.
- Ik kan een gebruikersgroep verwijderen.
- Eenmaal geopend, kan ik bij een gebruikersgroep de organisaties, informatiecategorieën en/of thema's (de)selecteren. (#5 )
- De documentatie is bijgewerkt (Read the Docs)

**Buiten scope / andere user stories**

- Het (ont)koppelen van gebruikers aan de gebruikersgroep is opgenomen in #31 .
- Logging / audittrail is opgenomen in #6 .
- Het verbergen van de beheerfunctionaliteit voor niet-beheerders pakken we t.z.t. apart op.

**Taken**

- [x] Groepsnaam aanpasbaar maken in groep detail formulier
- [x] Veld voor groepsomschrijving toevoegen aan groep detail formulier
- [x] Functie toevoegen om groep te verwijderen
- [x] Functie toevoegen om nieuwe groep te maken

**Comment by felixcicatt** [comment]
Een eerste versie van de backend (#20) staat in de branch [dynamische-groepen](https://github.com/GeneriekPublicatiePlatformWoo/Openbaar-Documenten-Publicatie-Component/tree/dynamische-groepen). Voorstel: deze twee stories samen oppakken. @nijmra kan dan aan de front-end werken en waar nodig de backend aanpassen, en @mstokericatt kan dan zowel de backend als de frontend reviewen.

**Comment by MarcoKlerks** [comment]
> De documentatie is bijgewerkt (Read the Docs)

Niet gerealiseerd, maar we hebben dan ook überhaupt nog geen plek à la readthedocs voor de documentatie. Dit neem ik mee in een aparte story.
