### ISSUE TITLE
ODPC: documenten toevoegen/verwijderen bij bestaande publicatie

### ISSUE THREAD

**Issue by MarcoKlerks** [GeneriekPublicatiePlatformWoo/Openbaar-Documenten-Publicatie-Component#38]
In #23 hebben we het mogelijk gemaakt om meerdere documenten aan een publicatie toe te voegen aan een nieuwe publicatie. In #29 hebben we het mogelijk gemaakt om enkele gegevens van een bestaande publicatie te wijzigen. In deze story breiden we dit mutatie-scherm uit met de mogelijkheid om bij bestaande publicaties documenten toe te voegen of te wijzigen.

**Acceptatie criteria**

- In het mutatie-scherm ziet een gebruiker welke documenten aan een publicatie hangen.
- In het mutatie-scherm ziet de gebruiker o.a. de `publicatiestatus` van de documenten.
- Een gebruiker kan de metadata van een document wijzigen.
- Een gebruiker kan een of meer documenten toevoegen incl. metadata.
- Een gebruiker kan een of meer documenten intrekken.
  - Dit leidt **niet** tot een delete uit de ODRC, maar..
  - bij het document wordt de publicatiestatus ([ODRC #49](https://github.com/GeneriekPublicatiePlatformWoo/registratie-component/issues/49)) op 'ingetrokken' gezet.
  - Een gebruiker kan een 'ingetrokken' document weer op 'gepubliceerd' zetten. **Dit in tegenstelling tot een Publicatie**

**Notities**
- NB: er is een belangrijk verschil tussen een reeds opgeslagen document en een document dat je nog niet opgeslagen hebt: Totdat je een document hebt opgeslagen, mag je m nog verwijderen, daarna alleen intrekken.

**Taken**

- [ ]

**Comment by MarcoKlerks** [comment]
@nijmra 

Testresultaten:

1. Een ingetrokken document krijgt een lichtgrijze kleur i.p.v. een lichtpaarse kleur. Het is mogelijk voor gebruikers niet helder wat de kleuren betekenen. De kleurverschillen zijn sowieso niet goed zichtbaar voor gebruikers met een visuele beperking (bijv. kleurenblindheid). Graag bij een ingetrokken document de bestandsnaam doorstrepen en erbij schrijven "(ingetrokken)".
2. Verder prima. Getest met meerdere documenten tegelijkertijd. Getest met verschillende mutaties tegelijkertijd.

**Comment by nijmra** [comment]
@MarcoKlerks

Opmerking m.b.t. tonen ingetrokken document meegenomen in deze versie.

Aanpassing staat op https://odpc.accept.icatt.nl
