### ISSUE TITLE
ODPC: Zet status bij nieuwe publicatie / document

### ISSUE THREAD

**Issue by MarcoKlerks** [GeneriekPublicatiePlatformWoo/Openbaar-Documenten-Publicatie-Component#41]
In [ODRC #49](https://github.com/GeneriekPublicatiePlatformWoo/registratie-component/issues/49) wordt een nieuw attribuut `publicatiestatus' aan de publicatie en aan het document toegevoegd. Bij een nieuwe publicatie / document moet deze de waarde "gepubliceerd" krijgen.

**Acceptatie criteria**

- Bij een nieuwe publicatie wordt in de API-call ook de publicatiestatus "gepubliceerd" meegegeven.
- Bij een nieuw document wordt in de API-call ook de publicatiestatus "gepubliceerd" meegegeven.

**Taken**

- [ ] Voeg status veld toe aan de mock voor publicaties indien we daar nog mee werken
- [ ] Voeg status veld toe aan de mock voor documenten indien we daar nog mee werken
- [ ] Stuur vanuit de front end de status `gepubliceerd` mee bij nieuwe publicaties
- [ ] Stuur vanuit de front end de status `gepubliceerd` mee bij nieuwe documenten

**Comment by felixcicatt** [comment]
Wordt hoogstwaarschijnlijk al geïmplementeerd binnen #23
