### ISSUE TITLE
ODPC: Groep autoriseren voor informatiecategorieën

### ISSUE THREAD

**Issue by MarcoKlerks** [GeneriekPublicatiePlatformWoo/Openbaar-Documenten-Publicatie-Component#46]
Als beheerder wil ik een gebruikersgroep kunnen autoriseren voor één of meer informatiecategorieën, zodat (later) een lid van deze gebruikersgroep deze informatiecategorieën kan toekennen aan een publicatie.

**Acceptatie criteria**

- Het ODRC wordt gebruikt als bron voor de informatiecategorieën. Zie [ODRC #14](https://github.com/GeneriekPublicatiePlatformWoo/registratie-component/issues/14).
- Vanuit de beheer-interface kan bij een autorisatiegroep een of meer informatiecategorieën geselecteerd worden. Zie #5 .
- De autorisaties op informatiecategorieën worden opgeslagen. Zie #20.
- De wijzigingen worden gelogd. Zie #6.

**Taken**

- [ ]

**Comment by RutgerICATT** [comment]
@MarcoKlerks: Deze story is al gerealiseerd in een van de eerdere stories.
