### ISSUE TITLE
ODPC: Informatiecategorieën toekennen aan publicatie

### ISSUE THREAD

**Issue by MarcoKlerks** [GeneriekPublicatiePlatformWoo/Openbaar-Documenten-Publicatie-Component#47]
Als medewerker wil ik één of meer informatiecategorieën kunnen koppelen aan een publicatie, zodat de publicatie gevonden kan worden door de burger als hij/zij zoekt op informatiecategorie.

Let op! [ODRC #48](https://github.com/GeneriekPublicatiePlatformWoo/registratie-component/issues/48) is randvoorwaardelijk.

**Acceptatie criteria**

- Bij het aanmaken van een publicatie (#34) kan een gebruiker een of meer (minstens één) informatiecategorieën selecteren.
- Bij het muteren van een publicatie kan een gebruiker informatiecategorieën (de)selecteren (#9). Minstens één moet er over blijven.
- Een gebruiker ziet alleen de informatiecategorieën waarvoor hij/zij via de autorisatiegroep voor geautoriseerd is. (#46).
- De geselecteerde informatiecategorieën worden meegegeven aan de ODRC-API ([ODRC #48](https://github.com/GeneriekPublicatiePlatformWoo/registratie-component/issues/48)).
- Foutmelding als er geen informatiecategorieën getoond kunnen worden (bijv. wanneer de API eruit ligt of wanneer de autorisatiegroep voor geen informatiecategorie geautoriseerd is)
- Foutmelding wanneer er bij het opslaan geen informatiecategorie is geselecteerd.

**Taken**

- [x] Informatiecategorieën samenstellen/filteren op basis van gebruikers groepen van de ingelogde gebruiker aan backend, ontsluiten via nieuw endpoint
- [x] Lijst tonen
- [x] Check op minimaal 1 categorie (frontend en backend)
- [x] Backend valideren of er geen Informatiecategorie toegevoegd wordt die niet mag

**Comment by nijmra** [comment]
@MarcoKlerks deze story is door ons refined, wil jij m nog checken/acceptatiecriteria doorlopen en indien duidelijk op ready zetten?

**Comment by MarcoKlerks** [comment]
> > [@MarcoKlerks](https://github.com/MarcoKlerks) Stel je zit in groep A. . Je maakt een publicatie aan met informatiecategorie1, die gekoppeld is aan groep A. Vervolgens wordt informatiecategorie 1 ontkoppeld van groep A. Wat betekent dit voor de eerdere publicatie? Mag die nog in je lijst met publicaties staan? Mag je deze publicatie nog wijzigen? Moet je eerst een andere informatiecategorie kiezen voordat je weer mag opslaan?
> 
> @MarcoKlerks deze vraag heb je al beantwoord toch? Eventuele discrepanties worden opgelost door functioneel beheerder?

Ja, dit scenario is voorlopig voor FB. Later kunnen we dit mogelijk nog mooier maken. Hiervoor heb ik #78 toegevoegd.

P.S. Goed dat jullie dit soort scenario's benoemen. Dat helpt om (later) de kwaliteit van de software te verbeteren!

**Comment by MarcoKlerks** [comment]
Ik kan niet meer testen, want door #74 hkan ik niet meer bij de gebruikersgroepen.

**Comment by MarcoKlerks** [comment]
Testresultaten:

1. Als ik zonder autorisaties probeer een nieuwe publicatie aan te maken, dan krijg ik een foutmelding: _"U bent niet gekoppeld aan een actieve gebruikersgroep."_ Heel goed! Graag nog een zin aan toevoegen: _"Neem contact op met uw beheerder."_
2. Ik heb ook even het bovenstaande scenario getest. Ik kreeg terecht de onderstaande foutmelding. Graag de tekst aanpassen naar: _"De publicatie kon niet worden opgeslagen. Probeer het nogmaals of neem contact op met uw beheerder."_

![Image](https://github.com/user-attachments/assets/2444f1b4-11b9-405f-b8c6-46b260159b3c)

3. "De geselecteerde informatiecategorieën worden meegegeven aan de ODRC-API ([#48](https://github.com/GeneriekPublicatiePlatformWoo/registratie-component/issues/48))." kon ik nog niet testen, want die user story op de ODRC is nog niet uitgevoerd. Testen we t.z.t. wel.

Twee tekstuele wijzigingen op de foutmeldingen dus.

Overigens zie ik dat een aantal verbeteringen zijn aangebracht op de presentatie van de publicaties en documenten! Heel goed! Dat gaat helpen om het scherm overzichtelijk te houden, naarmate we gaan uitbreiden. 👍
