### ISSUE TITLE
ODPC: Gebruikersgroep autoriseren

### ISSUE THREAD

**Issue by RutgerICATT** [GeneriekPublicatiePlatformWoo/Openbaar-Documenten-Publicatie-Component#5]
**Description (why)**
Van gebruikersgroepen moet vastgelegd worden voor welke organisaties, thema's en informatiecategorieën ze mogen publiceren. De organisaties, thema's en informatiecategorieën komen uit de registratiecomponent van Maykin. Voor de groepen is nog niet duidelijk waar ze vandaan komen. Binnen deze story gaan we uit van hard coded groepen, in een vervolgstory gaan we de groepen ophalen uit de daarvoor gekozen bron. Het gaat binnen [de Wireframe](https://app.uizard.io/p/8dd0f9fa/fullscreen) om het detailscherm van een groep.

[Hier staat een eerste opzet van hoe de waardelijsten er uit gaan zien in de Registratie component](https://github.com/GeneriekPublicatiePlatformWoo/registratie-component/issues/14#issue-2502356496)

Bij het uitvoeren van deze story gaan we er vanuit dat iedereen dit scherm kan zien en gebruiken. Autorisatie op de Beheerder rol komt later.

Foutafhandeling: als er een waardelijst niet kan worden opgehaald of het formulier kan niet worden opgeslagen, komt er een generieke foutmelding in het scherm. Als het formulier niet kan worden opgeslagen, kan je het opnieuw proberen

Documentatie van alle configuratie / environment variabelen met voorbeelden. In eerste instantie in een `installation.md` bestand in de ODPC github repository.

We laten nl design system voor de eerste schermen even los, dit is ook geen vereiste voor de publicatiecomponent.

**Schatting**:  

uit PSA: Een gebruikersgroep is alleen zinvol als deze ergens voor 
geautoriseerd kan worden

**Acceptance criteria (what)**

**Specific details (how)**
- Eerste story die Database vereist
- Eerste story die koppeling met Registreren OF Keycloak vereist (OF we doen dit in de eigen database?)
- Gegevens ophalen uit Keycloak OF Registreren OF Eigen database:
  - Groepen
- Lijsten ophalen uit Registreren:
  - Organisaties
  - Informatiecategorieen
  - Thema's
- Koppelen groepen (id) met items uit lijsten (id) in Database
- Schermen:
  - Lijst met groepen (naam), sorteren op naam
  - Groep detail met daarop formulier:
  - Checkbox Organisaties
  - Checkbox Informatiecategorieen
  - Checkbox Themas
**Test plan**

**Taken**

- [ ] endpoint voor het ophalen van (hardcoded) groepen
- [ ] endpoint voor het ophalen van (hardcoded) organisaties, thema's en informatiecategorien
- [ ] endpoints voor het opslaan en ophalen van aan groepen gelinkte organisaties, thema's en informatiecategorien. 
- [ ] story toevoegen voor het integreren met het ODCR

**Comment by MarcoKlerks** [comment]
Feedback n.a.v. de Wireframe:
- Graag rechtsboven eerst de link "Publicaties" en dan rechts daarvan "Gebruikersgroepen". Die laatste link mag ook "Admin" heten of iets dergelijks.
- Graag de kolommen "Thema's" en "Informatiecategorieën" omwisselen.
- Graag per kolom de optie aanbieden om met één muisklik alles aan/uit te vinken.
- In de [waardenlijst](https://standaarden.overheid.nl/tooi/waardelijsten/expression?lijst_uri=https%3A%2F%2Fidentifier.overheid.nl%2Ftooi%2Fset%2Fscw_toplijst%2F1) zie je hoofdthema's en subthema's. In de kolom "Thema's" kunnen we daar vast ook iets moois mee om de lange lijst overzichtelijk te houden. In het ODRC wordt daar ook al rekening mee gehouden ([user story](https://github.com/GeneriekPublicatiePlatformWoo/registratie-component/issues/11)).
