### ISSUE TITLE
ODPC: Informatiecategorieën koppelen aan publicaties

### ISSUE THREAD

**Issue by MarcoKlerks** [GeneriekPublicatiePlatformWoo/Openbaar-Documenten-Publicatie-Component#59]
Als medewerker wil ik aan mijn publicatie informatiecategorieën kunnen koppelen, zodat de burger later deze publicatie kan vinden wanneer hij/zij/hen zoekt op informatiecategorie.

**Acceptatie criteria**

- Bij het aanmaken van een nieuwe publicatie kan de gebruiker een of meer informatiecategorieën koppelen,
- Het koppelen van minstens één informatiecategorie is WEL verplicht.
- Een informatiecategorie kan ook weer ontkoppeld worden.
- De ingelogde gebruiker ziet alleen informatiecategorieën waarvoor de gebruiker via de autorisatiegroepen geautoriseerd is:
  - Als de gebruiker lid is van meerdere autorisatiegroepen, dan worden alle informatiecategorieën getoond waarvoor minstens één van deze autorisatiegroepen geautoriseerd is. 
- Bij het wijzigen van een publicatie kunnen eveneens informatiecategorieën gekoppeld of ontkoppeld worden, conform autorisaties.

Als de informatiecategorieën nog niet uit het ODRC opgehaald worden, maar er nog wordt gewerkt met dummy-data, voeg dan een user story aan de backlog toe om dit later alsnog te realiseren.

**Taken**

- [ ]

**Comment by RutgerICATT** [comment]
@MarcoKlerks Deze is duplicaat van #47

**Comment by MarcoKlerks** [comment]
Ik word dement...
