### ISSUE TITLE
ODPC: organisaties ophalen uit ODRC

### ISSUE THREAD

**Issue by MarcoKlerks** [GeneriekPublicatiePlatformWoo/Openbaar-Documenten-Publicatie-Component#63]
Let op! [ODRC #26](https://github.com/GeneriekPublicatiePlatformWoo/registratie-component/issues/26) is randvoorwaardelijk.

**Acceptatie criteria**

- Bij de autorisatiegroepen worden de organisaties getoond, zoals ze opgeslagen zijn in het ODRC (i.p.v. dummy-data)
- Dummy-data zijn opgeschoond / verwijderd
- Het autoriseren op organisaties werkt nog steeds
~~- Het loggen van wijzigingen in autorisaties werkt nog steeds~~

**Taken**

- [x] Het endpoint voor organisaties in ODPC aanpassen zodat de organisaties uit het ODRC komen, vergelijkbaar met het endpoint voor informatiecategorieen
- [x] De organisaties mock opruimen
- [x] Eventuele afwijkingen in property namen oplossen in de frontend

**Comment by felixcicatt** [comment]
@MarcoKlerks ik heb het acceptatiecriterium voor loggen van wijzigingen doorgestreept, omdat we dat bij mijn weten (nog) niet gaan doen in P0.
