### ISSUE TITLE
ODPC: Aanmaken (concept-)publicatie

### ISSUE THREAD

**Issue by RutgerICATT** [GeneriekPublicatiePlatformWoo/Openbaar-Documenten-Publicatie-Component#7]
**Description (why)**
Een ambtenaar moet publicaties aan kunnen maken voor de organisaties/informatiecategorieën/thema's waarvoor deze ambtenaar geautoriseerd is op basis van de autorisatiegroepen waarbij de ambtenaar hoort.

De groepen van de ingelogde gebruiker komen in een claim in de JWT token. Deze lezen we uit en gebruiken we om te bepalen voor welke organisaties/informatiecategorieën/thema's de gebruiker geautoriseerd is.

Zie publicatie detail scherm op https://app.uizard.io/prototypes/YO6yaXnzXKC7AdZgWr8J/player/fullscreen

Foutafhandeling: als er een waardenlijst niet kan worden opgehaald of het formulier kan niet worden opgeslagen, komt er een generieke foutmelding in het scherm. Als het formulier niet kan worden opgeslagen, kan je het opnieuw proberen.

Als je sessie verlopen is, krijg je de optie om opnieuw in te loggen en het opnieuw te proberen (zonder dat je werk verliest).

Documentatie van alle configuratie / environment variabelen met voorbeelden. In eerste instantie in een installation.md bestand in de ODPC github repository.

**Splitsen**
- [x] #22
  - Enkel bestand, zonder validatie op bestandsgrootte / -type 
  - Creatiedatum
  - Geldigheid
  - Dummy waardes voor overige verplichte velden
  - Publicatie is zichtbaar in de Registratiecomponent
  -  **3 punten**
- [x] #23
  - **2 punten**
- [ ] #24
  - Organisaties
  - Informatiecategorieën
  - Thema's
  - **3 punten**
- [ ] #25
  - **1 punt** 
- [ ] #26
  - **2 punten**
- [ ] #27
  - **1 punt**
- [x] #28
  - **1 punt**

**Acceptance criteria (what)**

**Specific details (how)**
- Dit mag de `Ambtenaar`, (ook de `Beheerder`?)
- Scherm met formulier
  - Officiële titel (tekst)
  - Creatiedatum (datum input)
  - Geldigheid (datum input)
  - documenthandeling (fieldset): <mark>dit zijn er waarschijnlijk 0 of meer. uitzoeken</mark>
    - soort handeling (radiobutton) (ondertekening, ontvangst, vaststelling)
    - tijd van handeling (datum tijd input) 
  - [Documentsoort](https://standaarden.overheid.nl/diwoo/metadata/doc/0.9.4/diwoo-metadata-lijsten_xsd_Simple_Type_diwoo_documentsoortlijst#documentsoortlijst)
  - Radiobutton <mark>(of checkbox?)</mark> Organisaties waarvoor gebruiker geautoriseerd is
  - Radiobutton <mark>(of checkbox?)</mark> Informatiecategorieën waarvoor gebruiker geautoriseerd is
  - Checkbox Thema's waarvoor gebruiker geautoriseerd is
  - Bestanden uploaden (multiple file input)
  - Knop Definitief opslaan
  - Knop Concept opslaan
  - Knop Annuleren
- Opslaan in registratiecomponent
- Loggen in logging tabel als die er al is
- Testen kan door check in admin omgeving `Registreren`

**Test plan**

**Comment by felixcicatt** [comment]
Deze informatie wil ik morgen verwerken:

TOOI veld 'documenthandeling'
Met een <documenthandeling> kan worden aangegeven op welke datum een officiële handeling met betrekking tot het document heeft plaatsgevonden.

Documenthandelingen zijn samengesteld uit een datum, een handeling en een voor de handeling verantwoordelijke organisatie. Aan actieve openbaarmaking in termen van de WOO ligt altijd minimaal één documenthandeling ten grondslag, daarom is dit veld verplicht; meerdere documenthandelingen kunnen worden toegekend aan één document.



TOOI veld 'informatiecategorie'
Van elk document dient de corresponderende informatiecategorie bekend te zijn. Dit kan door opname van TOOI veld <informatiecategorie>. Het is hierbij mogelijk om een document aan meerdere informatiecategorieën te relateren.



Document soorten 0...
Informatie categorie 1...
Themas 0...


Losse velden uitgever (verplicht) en verantwoordelijke (optioneel)
