### ISSUE TITLE
ODPC: Overzicht van eigen publicaties

### ISSUE THREAD

**Issue by RutgerICATT** [GeneriekPublicatiePlatformWoo/Openbaar-Documenten-Publicatie-Component#8]
**Description (why)**
uit PSA: Ook wil de gebruiker een overzicht van al zijn/haar/hen bestaande (concept-)publicaties. 

**Acceptance criteria (what)**

- Een medewerker kan een lijst van alle publicaties zien, **die hij/zij zelf heeft aangemaakt (!)**.
  - Getoond worden de `identifier`, `verkorteTitel `, `officieleTitel` en de datum waarop de registratie is aangemaakt. **is al gerealiseerd**
  - De lijst is standaard geordend van nieuw naar oud. **is al gerealiseerd**
  - Er wordt pagination toegepast.
  - Er kan ~gezocht worden op `identifier` en~  gefilterd worden (van/tot) op de datum waarop de registratie is aangemaakt, zie [ODRC story 68](https://github.com/GeneriekPublicatiePlatformWoo/registratie-component/issues/68).
  - Er kan gezocht worden op (een deel van de) `verkorteTitel ` en/of `officieleTitel` in een enkel zoekveld,  zie [ODRC story 68](https://github.com/GeneriekPublicatiePlatformWoo/registratie-component/issues/68)

**Test plan**

**Notities**
- We moeten nog bepalen hoe we vastleggen wie de publicatie heeft aangemaakt. Er komt een vervolgstory (#35 => #66) voor de koppeling van het publicatieoverzicht aan de registratiecomponent. Daarin stemmen we dit af.
- Filter op identifier lijkt niet logisch, dit wordt gegenereerd door de registratiecomponent. Voor de schatting nemen we aan dat dit niet hoeft.
- Sorteren op `officieleTitel` / `verkorteTitel ` / `registratiedatum` (asc/desc) toegevoegd, al beschikbaar in ODRC.

**Taken**
- [ ] ~~Bij een publicatie vastleggen wie deze gemaakt heeft (geven we mee vanuit backend, hoeft de frontend niets mee)~~ Wordt opgepakt in #66
- [ ] ~~Bij het ophalen van de lijst met publicaties als query parameter meegeven wie de ingelogde gebruiker is (geven we mee vanuit backend, hoeft de frontend niets mee) (in eerste instantie filteren binnen de mock)~~ Wordt opgepakt in #66
- [x] Vanuit de mock pagineren op de backend
- [x] Zoeken en filteren vanuit de backend
- [x] Paginering doorvoeren op de frontend
- [x] Zoeken en filteren implementeren op de frontend en doorgeven aan de backend

**Comment by MarcoKlerks** [comment]
Getest. Prima! Ik heb story 68 een hogere prio gegeven.
