### ISSUE TITLE
ODPC: muteren bestaande publicatie

### ISSUE THREAD

**Issue by RutgerICATT** [GeneriekPublicatiePlatformWoo/Openbaar-Documenten-Publicatie-Component#9]
**Description (why)**
Ik wil een bestaande publicatie muteren.
~~uit PSA: De gebruiker wil zo’n (concept-)publicatie kunnen muteren, publiceren of intrekken.~~

**Acceptance criteria (what)**

- In het overzicht van eigen publicaties (#8) kan een gebruiker een publicatie aanklikken en openen.
- Bij het openen verschijnt er een registratiescherm met de velden (zie #34):
  - "ID"
  - "Korte titel"
  - "Officiële titel"
  - "Omschrijving"
 - De velden tonen de huidige waarden.
 - Het "ID" is immutable, in de andere velden kunnen de waarden wel aangepast worden.
 - De "Officiële titel" is verplicht. De "Korte titel" en "Omschrijving" zijn optioneel.
 - De gebruiker kan de wijzigingen opslaan of annuleren.
 - Na opslaan of annuleren keert de gebruiker terug naar het (eventueel gefilterde) overzicht.

**Specific details (how)**
We hanteren het bestaande uuid veld uit de mock. Zodra we gaan koppelen met de registratiecomponent, kiezen we het veld wat we hiervoor moeten gebruiken.

**Taken**
- [x] uuid veld (read only) toevoegen aan het publicatieformulier voor bestaande publicaties
- [x] navigate handler om terug te keren naar (eventueel gefilterd) overzicht

**Test plan**

**Comment by felixcicatt** [comment]
Ik heb de indruk dat aan alle acceptatiecriteria van deze story al voldaan wordt (zij het met een mock), behalve het ID veld.
